services:
  - type: web
    name: minesweeper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent --worker-connections 1000 --timeout 120 wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: WEB_CONCURRENCY
        value: 1
      - key: GEVENT_SUPPORT
        value: "True" 