services:
  - type: web
    name: minesweeper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: WEB_CONCURRENCY
        value: 1 